__version__   = "2.4.13"
__app_name__  = "Inglorious Network Scanner"
__short_name__ = "INS"
__org__       = "Inglorious Labs"
GITHUB_REPO   = "mrsausagerolls/netscan"
LAUNCH_LABEL  = "co.ingloriouslabs.netscan"
